name: Test & Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
      - name: Lint
        run: pnpx run eslint .